sudo: required
dist: xenial
addons:
  firefox: latest-esr

cache:
  directories:
    - './user-application/node_modules'
    - './server/node_modules'

services:
  - xvfb

matrix:
  include:
    - language: node_js
      node_js:
        - "11"
      before_install:
        - cd './user-application'
      install:
        - npm install -g ionic cordova
        - npm install
      script:
        - ng test --watch=false

    - language: python
      python:
        - "3.7"  
      before_install:
        - cd './server'
      install:
        - pip install -r requirements.txt
      script:
        - python3 tests.py
